version: "3"

services:
  stardog:
    build: .
    environment:
      - STARDOG_SERVER_JAVA_ARGS=-Xmx3g -Xms3g -XX:MaxDirectMemorySize=6g -Dlog4j2.formatMsgNoLookups=true
    user: "1001:1002"
    ports:
      - 8081:5820
    volumes:
      - ~/volumes/stardog-home:/var/opt/stardog

  studio:
    image: docker.io/stardog/stardog-studio:3.0.1
    ports:
      - 8080:8080
