version: "3"

services:
  stardog:
    build: .
    environment:
      - STARDOG_SERVER_JAVA_ARGS=-Xmx4g -Xms4g -XX:MaxDirectMemorySize=8g
    ports:
      - 5820:5820
    volumes:
      - ./volumes/stardog:/var/opt/stardog

  studio:
    image: docker.io/stardog/stardog-studio:3.0.1
    ports:
      - 5821:8080
